name = "PoissonSolver"
uuid = "333ac5fb-9ca8-4109-ae2c-88ac1dd5ecab"
authors = ["Thomas Burton <tburton5572@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
